name: Publish to NuGet.org

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x

    - name: Chmod script 
      run: chmod +x ./versionNumberUtil.sh
      
    - name: Update version number
      run: ./versionNumberUtil.sh

    - name: Commit proj file
      uses: EndBug/add-and-commit@v9
      with: 
        add : '.'
        default_author: user_info
        message : "Update Version Number."

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build and pack
      run: dotnet pack --configuration Release --output ./artifacts

    - name: Publish to NuGet.org
      run: dotnet nuget push ./artifacts/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{secrets.NUGET_API_KEY}}
